parameters:
   type:
        Texte: Text
        Zone de texte: Textarea
        Url: Url
        E-mail: Email
        Nombre: Number
        Pourcentage: Percent
        Téléphone: Tel

easy_admin:
    entities:
        Champ:
            class: App\Entity\Champ
            label: 'Champs'
            list:
                help: 'Les champs sont utilisés par les modules'
                sort: 'nom'
                fields:
                    - id
                    - nom
                    - type
            search:
                sort: 'nom'
                fields:
                    - id
                    - nom
                    - type
            show:
                fields:
                    - id
                    - nom
                    - type
            form:
                fields:
                    - nom
                    - { property : 'type', type: 'choice', type_options: { expanded: false, choices: '%type%' } }
