easy_admin:
    entities:
        PagesActives:
            class: App\Entity\Page
            label: 'Pages'
            list:
                dql_filter: 'entity.corbeille = false'
                sort: 'titre'
                fields:
                    - id
                    - titre
                    - auteur
                    - { property: 'categories', label: 'Catégories' }
                    - { property: 'dateCreation', label: 'Date de création' }
#                    - { property: 'datePublication', label: 'Date de publication' }
#                    - { property: 'datedePublication', label: 'Date de dépublication' }
                    - { property: 'seo.url', label: 'Url' }
                    - langue
                    - active
            search:
                fields:
                    - titre
                    - auteur
                    - categories
            show:
                fields:
                    - id
                    - titre
                    - contenu
                    - modules
                    - image
                    - auteur
                    - auteurDerniereModification
                    - categories
                    - dateCreation
                    - { property: 'datePublication', label: 'Date de publication' }
                    - { property: 'datedePublication', label: 'Date de dépublication' }
                    - pageParent
                    - langue
                    - pageOriginale
                    - pagesTraduites
                    - commentaires
                    - seo
                    - active
            form:
                fields:
                    - { type: 'section', label: 'Contenus' }
                    - titre
                    - contenu
                    - modules
                    - image
                    - { type: 'section', label: 'Historique' }
                    - datePublication
                    - dateDepublication
                    - { type: 'section', label: 'Arborescence' }
                    - categories
                    - pageParent
                    - active
                    - corbeille
                    - { type: 'section', label: 'SEO' }
                    - { type: 'section', label: 'Commentaires' }
                    - { type: 'section', label: 'Traduction' }
                    - langue
                    - pageOriginale
                    - pagesTraduites

        PagesCorbeille:
            class: App\Entity\Page
            label: 'Pages à la corbeille'
            list:
                dql_filter: 'entity.corbeille = true'